project:
  type: website
  output-dir: _site

website:
  title: "GenAI Engineering"
  site-url: "https://Shivam-Miglani.github.io/genai-blog/"
  navbar:
    search: true

format:
  html:
    respect-user-color-scheme: true
    theme: yeti
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto
