project:
  type: website
  output-dir: _site

website:
  title: "Full Stack GenAI"
  site-url: "https://shivam-miglani.github.io/genai-blog/"
  navbar:
    search: true
  page-footer:
    center: "[About](/about.html) · © 2025 Shivam Miglani"

execute:
  freeze: true

format:
  html:
    theme:
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
    toc: false
    code-copy: true
    code-overflow: wrap
    main-font: system-ui
    grid:
      body-width: 720px
      gutter-width: 1.5rem
    include-in-header:
    - text: |
        <style>
        #quarto-header nav.navbar > .container-fluid{
          padding-left: .75rem;
          padding-right: .75rem;
          max-width: calc(720px + 1.5rem);
          margin: 0 auto;
        }
        </style>
