project:
  type: website
  output-dir: _site
  pre-render: add_license.py

website:
  title: "My Context Window"
  site-url: "https://shivam-miglani.github.io/genai-blog/"
  navbar:
    search: true
  page-footer:
    center: "[About](/about.html) · © {{< meta copyright.year >}} {{< meta copyright.holder >}}"

copyright:
  holder: "Shivam Miglani"
  year: 2025

execute:
  freeze: true
  eval: true

format:
  html:
    theme:
      light: [flatly, light.scss]
    highlight-style: printing # monokai
    toc: false
    code-copy: true
    code-overflow: wrap
    main-font: system-ui
    grid:
      body-width: 800px
      gutter-width: 1.5rem
    include-in-header:
    - text: |
        <style>
        #quarto-header nav.navbar > .container-fluid{
          padding-left: .75rem;
          padding-right: .75rem;
          max-width: calc(800px + 1.5rem);
          margin: 0 auto;
        }
        </style>
    include-after-body: notebook-footer.html
