project:
  type: website
  output-dir: _site

website:
  title: "GenAI Engineering"
  site-url: "https://Shivam-Miglani.github.io/genai-blog/"
  navbar:
    search: true
    background: primary
    foreground: primary

format:
  html:
    theme:
      light: [cosmo, light.scss]
      dark: [slate, dark.scss]
    css: styles.css
    mainfont: "Inter"
    code-copy: true

execute:
  freeze: true
